CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,) #just one!!
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 0 #6
PRINT_FREQ: 10

DATASET:
  DATASET: custom
  ROOT: data/
  TEST_SET: 'list/custom/val.lst'
  TRAIN_SET: 'list/custom/train.lst'
  NUM_CLASSES: 3
MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 2 #wtf is this just leave it be! 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar" #change this to cityscape pretrained
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE: #something with crop (revisit!)
  - 720
  - 720
  BASE_SIZE: 1280
  BATCH_SIZE_PER_GPU: 4 #6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 484
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 1280
  - 720
  BASE_SIZE: 720
  BATCH_SIZE_PER_GPU: 3 #6
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1